// community list — entries are added with `node upload.js` at the repo root

const EMAIL = 'ridellazorreply@gmail.com';

// slug -> profile page, so an author name can link to their page
let people = {};

function findPerson(author) {
  if (!author) return null;
  const needle = author.trim().toLowerCase();
  return people[needle] || null;
}

function setCount(count) {
  const el = document.getElementById('siteCount');
  if (el) el.textContent = count === 1 ? '1 project' : count + ' projects';
}

function writeNote(message) {
  const p = document.createElement('p');
  p.className = 'note';
  p.textContent = message;
  return p;
}

function renderItem(site) {
  // the row is a plain container, not a link, so the author can link to
  // their own profile without nesting anchors
  const row = document.createElement('div');
  row.className = 'item';

  const external = /^https?:\/\//i.test(site.url || '');

  const name = document.createElement('a');
  name.className = 'item-name';
  name.href = site.url || '#';
  name.textContent = site.name || 'Untitled';
  if (external) {
    name.target = '_blank';
    name.rel = 'noopener noreferrer';
  }
  row.appendChild(name);

  if (site.by) {
    const person = findPerson(site.by);
    const author = document.createElement(person ? 'a' : 'span');
    author.className = 'item-by';
    author.textContent = 'by ' + site.by;
    if (person)     author.href = 'people/' + person.slug + '/';
    row.appendChild(author);
  }

  if (site.description) {
    const text = document.createElement('span');
    text.className = 'item-desc';
    text.textContent = site.description;
    row.appendChild(text);
  }

  return row;
}

function render(sites) {
  const list = document.getElementById('communityList');
  if (!list) return;

  list.textContent = '';
  setCount(sites.length);

  if (!sites.length) {
    list.appendChild(writeNote('Nothing here yet. The first one is whatever you send over.'));
    return;
  }

  const frag = document.createDocumentFragment();
  sites.forEach(site => frag.appendChild(renderItem(site)));
  list.appendChild(frag);
}

// maps an author name to a profile folder. generated by profile.js — a missing
// file just leaves author names unlinked, which is fine.
fetch('people/index.json')
  .then(res => (res.ok ? res.json() : []))
  .then(list => {
    (Array.isArray(list) ? list : []).forEach(p => {
      if (!p || !p.slug) return;
      [p.slug, p.name, p.handle].forEach(k => {
        if (k) people[String(k).trim().toLowerCase()] = p;
      });
    });
  })
  .catch(() => {});

fetch('community.json')
  .then(res => {
    if (!res.ok) throw new Error('community.json responded ' + res.status);
    return res.json();
  })
  .then(data => render(Array.isArray(data) ? data : []))
  .catch(err => {
    console.error('Could not load community.json', err);
    const list = document.getElementById('communityList');
    if (!list) return;
    list.textContent = '';
    setCount(0);
    list.appendChild(writeNote('Could not load the list. Try again in a moment, or mail ' + EMAIL + '.'));
  });
